### ISSUE TITLE
background grid

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord-gedit#9]
Hello, thank you for all the work on Nord/Lumio, and for this Gedit theme that I use once in a while.

What's keeping me from using it everyday is that grid pattern isn't enabled. I'm too used to it as it helps me focusing on code. Would it be possible to add grid support?

Thanks :)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

Sorry for the delay, I've had no free time (job :man_health_worker:, study :book:, life :weight_lifting_man: etc.) to work on my or any other :octocat: OSS project (see Tweets :bird: from [April][t-april] and [June][t-june]), but from the beginning of July I finished my studies and can [finally spend time on OSS again][t-back] :green_heart:

I've implemented and merged the feature in PR #10. 

[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[t-back]: https://twitter.com/arcticicestudio/status/1010013091793256448

**Comment by ghost** [comment]
Hello, sorry to dig up this closed request, I don't know why I never replied to it, I probably was very busy and missed the notification, shame on me :fearful:

Just a suggestion: imho the grid color is a bit too harsh and contrasty, especially with commented text, maybe you could add a "nord1-darkened" color like what you did for "nord3-brightened". I tried several tints and I find that `#343842` is quite good, still visible but comfier. It's what I did when you added grid support, remembered it a couple of days ago after a reinstall...

_EDIT: opened a pull request, see below._
